# Generated by Django 6.1.1 on 2026-10-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikeservice_DB',
            fields=[
                ('Vehicle_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('DoR', models.DateField()),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('Vehicle_model', models.CharField(max_length=6)),
            ],
        ),
    ]
